*Data Mining with Rattle and R: The Art of Excavating Data for Knowledge Discovery* by Graham Williams

# References

Adler, J. (2010), *R in a Nutshell: A Desktop Reference Guide*, O’Reilly, Sebastopol.

Amaratunga, D., Cabrera, J., and Lee, Y.-S. (2008), Enriched random forests, *Bioinformatics* 24(18), 2010–2014.

Andrews, F. (2010), *latticist: A Graphical User Interface for Exploratory Visualization*. R package version 0.9-43. http://latticist.googlecode.com/.

Bauer, E. and Kohavi, R. (1999), An empirical comparison of voting classification algorithms: Bagging, boosting, and variants, *Machine Learning* 36(1–2), 105–139. http://citeseer.ist.psu.edu/bauer99empirical.html.

Bivand, R. S., Pebesma, E. J., and Gomez-Rubio, V. (2008), *Applied Spatial Data Analysis with R*, Use R!, Springer, New York.

Breiman, L. (1996), Bagging predictors, *Machine Learning* 24(2), 123– 140. http://citeseer.ist.psu.edu/breiman96bagging.html.

Breiman, L. (2001), Random forests, *Machine Learning* 45(1), 5–32.

Breiman, L., Friedman, J., Olshen, R., and Stone, C. (1984), *Classification and Regression Trees*, Wadsworth and Brooks, Monterey, CA.

Chambers, J. M. (2008), *Software for Data Analysis: Programming with R*, Springer, New York. http://stat.stanford.edu/~jmc4/Rbook/.

Cleveland, W. S. (1993), *Visualizing Data*, Hobart Press, Summit, NJ.

Cook, D. and Swayne, D. F. (2007), *Interactive and Dynamic Graphics for Data Analysis*, Springer, New York.

Cowpertwait, P. S. P. and Metcalfe, A. V. (2009), *Introductory Time Series with R*, Springer, New York.

Crano, W. D. and Brewer, M. B. (2002), *Principles and Methods of Social Research*, Lawrence Erlbaum Associates, Mahwah, NJ.

CRISP-DM (1996), *Cross Industry Process — Data Mining*. http://www.crisp-dm.org/.

Culp, M., Johnson, K., and Michailidis, G. (2010), *ada: An R Package for Stochastic Boosting*. R package version 2.0-2. http://CRAN.R-project.org/package=ada.

Cypher, A., ed. (1993), *Watch What I Do: Programming by Demonstration*, The MIT Press, Cambridge, MA. http://www.acypher.com/wwid/WWIDToC.html.

Dalgaard, P. (2008), *Introductory Statistics with R*, 2nd ed., Statistics and Computing, Springer, New York.

DebRoy, S. and Bivand, R. (2011), *foreign: Read Data Stored by Minitab, S, SAS, SPSS, Stata, Systat, and dBase*. R package version 0.8-44. http://CRAN.R-project.org/package=foreign.

Durtschi, C., Hillison, W., and Pacini, C. (2004), The effective use of Benford’s law to assist in detecting fraud in accounting data, *Journal of Forensic Accounting* 5, 17–34.

Fraley, C. and Raftery, A. E. (2006), *MCLUST Version 3 for R: Normal Mixture Modeling and Model-Based Clustering*, Technical Report 504, Department of Statistics, University of Washington.

Freund, Y. and Mason, L. (1997), The alternating decision tree learning algorithm, in *Proceedings of the 16th International Conference on Machine Learning (ICML99)*, Bled, Slovenia, Morgan Kaufmann, San Francisco, CA, pp. 124–133.

Freund, Y. and Schapire, R. E. (1995), A decision-theoretic generalization of on-line learning and an application to boosting, in P. M. B. Vitanyi, ed., *Proceedings of the 2nd European Conference on Computational Learning Theory (EuroCOLT95)*, Barcelona, Spain, Vol. 904 of Lecture Notes in Computer Science, Springer, pp. 23–37. http://citeseer.ist.psu.edu/freund95decisiontheoretic.html.

Galton, F. (1885), Regression towards mediocrity in hereditary stature, *Journal of the Anthropological Institute* 15, 246–263.

Glade (1998), *A User Interface Designer*, open source. http://glade.gnome.org.

Gnome (1997), *The Free Software Desktop Project*, open source. http://glade.gnome.org/.

Guazzelli, A., Lin, W. C., and Jena, T. (2010), *PMML in Action*, CreateSpace, Charleston, SC.

Guazzelli, A., Zeller, M., Lin, W.-C., and Williams, G. (2009), PMML: An open standard for sharing models, *The R Journal* 1(1), 60–65. http://journal.r-project.org/2009-1/RJournal_ 2009-1_Guazzelli+et+al.pdf.

Hahsler, M., Buchta, C., Gruen, B., and Hornik, K. (2011), *arules: Mining Association Rules and Frequent Itemsets*. R package version 1.0-6. http://CRAN.R-project.org/.

Han, J. and Kamber, M. (2006), *Data Mining: Concepts and Techniques*, 2nd ed., Morgan Kaufmann, San Francisco, CA.

Harrell, Jr., F. E. (2010), *Hmisc: Harrell Miscellaneous*. R package version 3.8-3. http://CRAN.R-project.org/package=Hmisc.

Hastie, T., Tibshirani, R., and Friedman, J. (2001), *The Elements of Statistical Learning: Data Mining, Inference, and Prediction*, Springer Series in Statistics, Springer-Verlag, New York.

Hastie, T., Tibshirani, R., and Friedman, J. (2009), *The Elements of Statistical Learning: Data Mining, Inference, and Prediction*, 2 ed., Springer Series in Statistics, Springer, New York.

Hawkins, D. (1980), *Identification of Outliers*, Chapman and Hall, London.

Ho, T. K. (1995), Random decision forests, in *Proceedings of the 3rd International Conference on Document Analysis and Recognition*, Montreal, Canada, IEEE Copmuter Society, pp. 278–282.

Ho, T. K. (1998), The random subspace method for constructing decision forests, *IEEE Transactions on Pattern Analysis and Machine Intelligence* 20(8), 832–844.

Hornik, K., Buchta, C., and Zeileis, A. (2009), Open-source machine learning: R meets Weka, *Computational Statistics* 24(2), 225–232.

Hothorn, T., Buehlmann, P., Kneib, T., Schmid, M., and Hofner, B. (2011), *Model-Based Boosting*. R package version 2.0-10. http://CRAN.R-project.org/package=mboost.

Hothorn, T., Hornik, K., and Zeileis, A. (2006), Unbiased recursive partitioning: A conditional inference framework, *Journal of Computational and Graphical Statistics* 15(3), 651–674.

Inmon, W. H. (1996), *Building the Data Warehouse*, John Wiley and Sons, New York.

Jing, L., Ng, M. K., and Huang, J. Z. (2007), An entropy weighting k-means algorithm for subspace clustering of high-dimensional sparse data, *IEEE Transactions on Knowledge and Data Engineering* 19(8), 1026–1041.

Karatzoglou, A., Smola, A., Hornik, K., and Zeileis, A. (2004), kernlab – an S4 package for kernel methods in R, *Journal of Statistical Software* 11(9), 1–20. http://www.jstatsoft.org/v11/i09/.

Kleiber, C. and Zeileis, A. (2008), *Applied Econometrics with R*, Use R!, Springer, New York.

Kuhn, M., Weston, S., Coulter, N., Lenon, P., and Otles, Z. (2010), *odfWeave: Sweave Processing of Open Document Format (ODF) Files*. R package version 0.7.17. http://CRAN.R-project.org/package=odfWeave.

Kuhn, M., Wing, J., Weston, S., Williams, A., Keefer, C., and Engelhardt, A. (2011), *caret: Classification and Regression Training*. R package version 4.76. http://CRAN.R-project.org/package=caret.

Lang, D. T. (2011), *XML: Tools for Parsing and Generating XML Within R and S-Plus*. R package version 3.4-0. http://CRAN.R-project.org/ package=XML.

Lang, D. T., Swayne, D., Wickham, H., and Lawrence, M. (2011), *rggobi: Interface between R and GGobi*. R package version 2.1.17. http://CRAN.R-project.org/package=rggobi.

Lawrence, M. and Temple Lang, D. (2010), RGtk2: A graphical user interface toolkit for R, *Journal of Statistical Software* 37(8), 1–52. http://www.jstatsoft.org/v37/i08/.

Liaw, A. and Wiener, M. (2002), Classification and regression by randomforest, *R News* 2(3), 18–22. http://CRAN.R-project.org/doc/Rnews/.

Maechler, M., Rousseeuw, P., Struyf, A., and Hubert, M. (2005), *Cluster analysis basics and extensions*.

Maindonald, J. and Braun, J. (2007), *Data Analysis and Graphics Using R*, 2nd ed., Cambridge University Press, Cambridge. http://wwwmaths.anu.edu.au/~johnm/r-book.html.

Mingers, J. (1989), An empirical comparison of selection measures for decision-tree induction, *Machine Learning* 3(4), 319–342.

Muenchen, R. A. (2008), *R for SAS and SPSS Users*, Statistics and Computing, Springer, New York.

Organisation for Economic Co-operation and Development (OECD) (1980), *OECD Guidelines on the Protection of Privacy and Transborder Flows of Personal Data*. http://www.oecd.org/document/18/0, 3343,en_2649_34255_1815186_1_1_1_1,00.html.

Python (1989), *Programming language*, open source. http://www.python.org.

Quinlan, J. R. (1986), Induction of decision trees, *Machine Learning*
1(1), 81–106.

Quinlan, J. R. (1993), *C4.5: Programs for Machine Learning*, Morgan
Kaufmann, San Fransisco.

R Development Core Team (2011), *R: A Language and Environment for Statistical Computing*, R Foundation for Statistical Computing, Vienna. http://www.R-project.org/.

R Foundation for Statistical Computing (2008), *R: Regulatory Compliance and Validation Issues. A Guidance Document for the Use of R in Regulated Clinical Trial Environments*. http://www.r-project.org/doc/R-FDA.pdf.

Ridgeway, G. (2010), *gbm: Generalized Boosted Regression Models*. R package version 1.6-3.1. http://CRAN.R-project.org/package=gbm.

Ripley, B. and Lapsley, M. (2010), *RODBC: ODBC Database Access*. R package version 1.3-2. http://CRAN.R-project.org/package=RODBC.

Sarkar, D. (2008), *Lattice: Multivariate Data Visualisation with R*, Use R!, Springer, New York.

Schapire, R. E., Freund, Y., Bartlett, P., and Lee, W. S. (1997), Boosting the margin: A new explanation for the effectiveness of voting methods, in D. H. Fisher, ed., *Proceedings of the 14th International Conference on Machine Learning (ICML97)*, Nashville, Tennessee, Morgan Kaufmann, San Francisco, pp. 322–330. http://citeseer.ist.psu.edu/schapire97boosting.html.

Shi, T. and Horvath, S. (2006), Unsupervised learning with random forest predictors, *Journal of Computational and Graphical Statistics* 15(1), 118–138.

Sing, T., Sander, O., Beerenwinkel, N., and Lengauer, T. (2009), *ROCR: Visualizing the Performance of Scoring Classifiers*. R package version 1.0-4. http://CRAN.R-project.org/package=ROCR.

Spector, P. (2008), *Data Manipulation with R*, Use R!, Springer, New York.

Strobl, C., Boulesteix, A.-L., Zeileis, A., and Hothorn, T. (2007), Bias in random forest variable importance measures: Illustrations, sources and a solution, *BMC Bioinformatics* 8(25). http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1796903/.

Taverner, T., Verzani, J., and Conde, I. (2010), *RGtk2Extras: Data frame editor and dialog making wrapper for RGtk2*. R package.

Therneau, T. M. and Atkinson, B. (2011), *rpart: Recursive Partitioning*. R package version 3.1-50. http://CRAN.R-project.org/package=rpart.

Torgo, L. (2010), *Data Mining with R: Learning with Case Studies*, CRC Data Mining and Knowledge Discovery, Chapman and Hall, Boca Ranton, FL.

Tufte, E. R. (1985), *The Visual Display of Quantitative Information*, Graphics Press.

Tukey, J. W. (1977), *Exploratory Data Analysis*, Addison-Wesley, Reading, MA.

Tuszynski, J. (2009), *caTools*. R package version 1.10. http://CRAN.R-project.org/package=caTools.

van Buuren, S. and Groothuis-Oudshoorn, K. (2011), Mice: Multivariate imputation by chained equations in R, *Journal of Statistical Software*, forthcoming.

Venables, W. N. and Ripley, B. D. (2002), *Modern Applied Statistics with S*, 4th ed., Statistics and Computing, Springer, New York.

Warnes, G. R. (2011), *gdata: R Programming Tools for Data Manipulation*. R package version 2.8.2. http://CRAN.R-project.org/package=gdata.

White, D. (2010), *maptree: Mapping, Pruning, and Graphing Tree Models*. R package version 1.4-6. http://CRAN.R-project.org/package=maptree.

Wickham, H. (2007), Reshaping data with the reshape package, *Journal of Statistical Software* 21(12), 1–20. http://www.jstatsoft.org/v21/i12/paper.

Wickham, H. (2009), *ggplot2: Elegant Graphics for Data Analysis*, Use
R!, Springer.

Wickham, H., Cook, D., Buja, A., and Schloerke, B. (2010), *DescribeDisplay: R Interface to DescribeDisplay (GGobi plugin)*. R package version 0.2.2. http://CRAN.R-project.org/package=DescribeDisplay.

Wickham, H., Lawrence, M., Lang, D. T., and Swayne, D. F. (2008), An introduction to rggobi, *R News* 8(2), 3–7.

Williams, G. J. (1987), Some experiments in decision tree induction., *Australian Computer Journal* 19(2), 84–91.

Williams, G. J. (1988), Combining decision trees: Initial results from the MIL algorithm, in J. S. Gero and R. B. Stanton, eds., *Artificial Intelligence Developments and Applications: Selected Papers from the First Australian Joint Artificial Intelligence Conference, Sydney, Australia, 2–4 November, 1987*, Elsevier Science Publishers, North-Holland, pp. 273–289.

Williams, G. J. (2009), Rattle: A data mining GUI for R, *The R Journal* 1(2), 45–55. http://journal.r-project.org/archive/2009-2/RJournal_2009-2_Williams.pdf.

Williams, G. J., Huang, J. Z., Chen, X., and Wang, Q. (2011), *siat-clust: Shenzhen Institutes of Advanced Technology Clustering Suite*. R package version 1.0.0. http://www.siat.ac.cn.

Witten, I. H. and Frank, E. (2005), *Data Mining: Practical Machine Learning Tools and Techniques*, 2nd ed., Morgan Kaufmann, San Francisco. http://www.cs.waikato.ac.nz/~ml/weka/book.html.

Wuertz, D., Rmetrics core team members, Chauss, P., King, R., Gu, C., Gross, J., Scott, D., Lumley, T., Zeileis, A., and Aas, K. (2010), *fBasics: Rmetrics — Markets and Basic Statistics*. R package version 2110.79. http://CRAN.R-project.org/package=fBasics.
